apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collector
rules:
- apiGroups:
  - policy.open-cluster-management.io
  - cluster.open-cluster-management.io
  resources:
  - policies
  - policysets
  - placementdecisions
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: c2p
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collector
subjects:
- kind: ServiceAccount
  name: collector
  namespace: c2p