apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    policies.kyverno.io/category: Sample
    policies.kyverno.io/description: By default, images that have already been pulled
      can be accessed by other Pods without re-pulling them if the name and tag are
      known. In multi-tenant scenarios, this may be undesirable. This policy mutates
      all incoming Pods to set their imagePullPolicy to Always. An alternative to
      the Kubernetes admission controller AlwaysPullImages.
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/title: Always Pull Images
  name: always-pull-images
spec:
  background: false
  rules:
  - match:
      resources:
        kinds:
        - Pod
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - (name): ?*
            imagePullPolicy: Always
    name: always-pull-images
