apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-managed-kubernetes
  namespace: c2p
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: my-cluster
          operator: In
          values:
          - "true"
