apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: cm-2
    policy.open-cluster-management.io/standards: ""
  name: policy-deployment
  namespace: c2p
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-deployment
      spec:
        namespaceSelector:
          exclude:
          - kube-system
          - open-cluster-management
          - open-cluster-management-agent
          - open-cluster-management-agent-addon
          include:
          - '*'
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              labels:
                app: nginx
              name: nginx-deployment
            spec:
              replicas: 3
              selector:
                matchLabels:
                  app: nginx
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                  - image: nginx:1.21.4
                    name: nginx
                    ports:
                    - containerPort: 80
        remediationAction: inform
        severity: low
  remediationAction: inform
