apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kyverno
    app.kubernetes.io/component: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 2.6.5
    helm.sh/chart: kyverno-2.6.5
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: kyverno:admin-generaterequest
rules:
- apiGroups:
  - kyverno.io
  resources:
  - generaterequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
