# permissions for end users to view compliancedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: compliancedeployment-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: compliance-to-policy
    app.kubernetes.io/part-of: compliance-to-policy
    app.kubernetes.io/managed-by: kustomize
  name: compliancedeployment-viewer-role
rules:
- apiGroups:
  - compliance-to-policy.io
  resources:
  - compliancedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compliance-to-policy.io
  resources:
  - compliancedeployments/status
  verbs:
  - get
