# permissions for end users to edit controlreferences.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: controlreference-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: compliance-to-policy
    app.kubernetes.io/part-of: compliance-to-policy
    app.kubernetes.io/managed-by: kustomize
  name: controlreference-editor-role
rules:
- apiGroups:
  - compliance-to-policy.io
  resources:
  - controlreferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compliance-to-policy.io
  resources:
  - controlreferences/status
  verbs:
  - get
