//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 IBM Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Category) DeepCopyInto(out *Category) {
	*out = *in
	if in.Controls != nil {
		in, out := &in.Controls, &out.Controls
		*out = make([]Control, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Category.
func (in *Category) DeepCopy() *Category {
	if in == nil {
		return nil
	}
	out := new(Category)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSelectors) DeepCopyInto(out *ClusterSelectors) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSelectors.
func (in *ClusterSelectors) DeepCopy() *ClusterSelectors {
	if in == nil {
		return nil
	}
	out := new(ClusterSelectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Compliance) DeepCopyInto(out *Compliance) {
	*out = *in
	in.Standard.DeepCopyInto(&out.Standard)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Compliance.
func (in *Compliance) DeepCopy() *Compliance {
	if in == nil {
		return nil
	}
	out := new(Compliance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceDeployment) DeepCopyInto(out *ComplianceDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceDeployment.
func (in *ComplianceDeployment) DeepCopy() *ComplianceDeployment {
	if in == nil {
		return nil
	}
	out := new(ComplianceDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComplianceDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceDeploymentBinding) DeepCopyInto(out *ComplianceDeploymentBinding) {
	*out = *in
	if in.ClusterGroups != nil {
		in, out := &in.ClusterGroups, &out.ClusterGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceDeploymentBinding.
func (in *ComplianceDeploymentBinding) DeepCopy() *ComplianceDeploymentBinding {
	if in == nil {
		return nil
	}
	out := new(ComplianceDeploymentBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceDeploymentClusterGroup) DeepCopyInto(out *ComplianceDeploymentClusterGroup) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = new(map[string]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string]string, len(*in))
			for key, val := range *in {
				(*out)[key] = val
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceDeploymentClusterGroup.
func (in *ComplianceDeploymentClusterGroup) DeepCopy() *ComplianceDeploymentClusterGroup {
	if in == nil {
		return nil
	}
	out := new(ComplianceDeploymentClusterGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceDeploymentCompliance) DeepCopyInto(out *ComplianceDeploymentCompliance) {
	*out = *in
	out.Catalog = in.Catalog
	out.Profile = in.Profile
	out.ComponentDefinition = in.ComponentDefinition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceDeploymentCompliance.
func (in *ComplianceDeploymentCompliance) DeepCopy() *ComplianceDeploymentCompliance {
	if in == nil {
		return nil
	}
	out := new(ComplianceDeploymentCompliance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceDeploymentList) DeepCopyInto(out *ComplianceDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComplianceDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceDeploymentList.
func (in *ComplianceDeploymentList) DeepCopy() *ComplianceDeploymentList {
	if in == nil {
		return nil
	}
	out := new(ComplianceDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComplianceDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceDeploymentResourceRef) DeepCopyInto(out *ComplianceDeploymentResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceDeploymentResourceRef.
func (in *ComplianceDeploymentResourceRef) DeepCopy() *ComplianceDeploymentResourceRef {
	if in == nil {
		return nil
	}
	out := new(ComplianceDeploymentResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceDeploymentSpec) DeepCopyInto(out *ComplianceDeploymentSpec) {
	*out = *in
	out.Compliance = in.Compliance
	out.PolicyResources = in.PolicyResources
	if in.ClusterGroups != nil {
		in, out := &in.ClusterGroups, &out.ClusterGroups
		*out = make([]ComplianceDeploymentClusterGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Binding.DeepCopyInto(&out.Binding)
	out.Target = in.Target
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceDeploymentSpec.
func (in *ComplianceDeploymentSpec) DeepCopy() *ComplianceDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(ComplianceDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceDeploymentStatus) DeepCopyInto(out *ComplianceDeploymentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceDeploymentStatus.
func (in *ComplianceDeploymentStatus) DeepCopy() *ComplianceDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(ComplianceDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplianceDeploymentTarget) DeepCopyInto(out *ComplianceDeploymentTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplianceDeploymentTarget.
func (in *ComplianceDeploymentTarget) DeepCopy() *ComplianceDeploymentTarget {
	if in == nil {
		return nil
	}
	out := new(ComplianceDeploymentTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Control) DeepCopyInto(out *Control) {
	*out = *in
	if in.ControlRefs != nil {
		in, out := &in.ControlRefs, &out.ControlRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Control.
func (in *Control) DeepCopy() *Control {
	if in == nil {
		return nil
	}
	out := new(Control)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlReference) DeepCopyInto(out *ControlReference) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlReference.
func (in *ControlReference) DeepCopy() *ControlReference {
	if in == nil {
		return nil
	}
	out := new(ControlReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlReference) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlReferenceKcp) DeepCopyInto(out *ControlReferenceKcp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlReferenceKcp.
func (in *ControlReferenceKcp) DeepCopy() *ControlReferenceKcp {
	if in == nil {
		return nil
	}
	out := new(ControlReferenceKcp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlReferenceKcp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlReferenceKcpList) DeepCopyInto(out *ControlReferenceKcpList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlReferenceKcp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlReferenceKcpList.
func (in *ControlReferenceKcpList) DeepCopy() *ControlReferenceKcpList {
	if in == nil {
		return nil
	}
	out := new(ControlReferenceKcpList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlReferenceKcpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlReferenceKcpSpec) DeepCopyInto(out *ControlReferenceKcpSpec) {
	*out = *in
	in.Compliance.DeepCopyInto(&out.Compliance)
	in.Target.DeepCopyInto(&out.Target)
	out.PolicyResources = in.PolicyResources
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlReferenceKcpSpec.
func (in *ControlReferenceKcpSpec) DeepCopy() *ControlReferenceKcpSpec {
	if in == nil {
		return nil
	}
	out := new(ControlReferenceKcpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlReferenceKcpStatus) DeepCopyInto(out *ControlReferenceKcpStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlReferenceKcpStatus.
func (in *ControlReferenceKcpStatus) DeepCopy() *ControlReferenceKcpStatus {
	if in == nil {
		return nil
	}
	out := new(ControlReferenceKcpStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlReferenceKcpTarget) DeepCopyInto(out *ControlReferenceKcpTarget) {
	*out = *in
	if in.Workspaces != nil {
		in, out := &in.Workspaces, &out.Workspaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClusterGroups != nil {
		in, out := &in.ClusterGroups, &out.ClusterGroups
		*out = make([]ComplianceDeploymentClusterGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlReferenceKcpTarget.
func (in *ControlReferenceKcpTarget) DeepCopy() *ControlReferenceKcpTarget {
	if in == nil {
		return nil
	}
	out := new(ControlReferenceKcpTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlReferenceList) DeepCopyInto(out *ControlReferenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlReferenceList.
func (in *ControlReferenceList) DeepCopy() *ControlReferenceList {
	if in == nil {
		return nil
	}
	out := new(ControlReferenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlReferenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlReferenceSpec) DeepCopyInto(out *ControlReferenceSpec) {
	*out = *in
	in.Compliance.DeepCopyInto(&out.Compliance)
	out.Target = in.Target
	out.PolicyResources = in.PolicyResources
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlReferenceSpec.
func (in *ControlReferenceSpec) DeepCopy() *ControlReferenceSpec {
	if in == nil {
		return nil
	}
	out := new(ControlReferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlReferenceStatus) DeepCopyInto(out *ControlReferenceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlReferenceStatus.
func (in *ControlReferenceStatus) DeepCopy() *ControlReferenceStatus {
	if in == nil {
		return nil
	}
	out := new(ControlReferenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlReferenceTarget) DeepCopyInto(out *ControlReferenceTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlReferenceTarget.
func (in *ControlReferenceTarget) DeepCopy() *ControlReferenceTarget {
	if in == nil {
		return nil
	}
	out := new(ControlReferenceTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyReportRef) DeepCopyInto(out *PolicyReportRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyReportRef.
func (in *PolicyReportRef) DeepCopy() *PolicyReportRef {
	if in == nil {
		return nil
	}
	out := new(PolicyReportRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultCollector) DeepCopyInto(out *ResultCollector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultCollector.
func (in *ResultCollector) DeepCopy() *ResultCollector {
	if in == nil {
		return nil
	}
	out := new(ResultCollector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResultCollector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultCollectorList) DeepCopyInto(out *ResultCollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ResultCollector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultCollectorList.
func (in *ResultCollectorList) DeepCopy() *ResultCollectorList {
	if in == nil {
		return nil
	}
	out := new(ResultCollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ResultCollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultCollectorSpec) DeepCopyInto(out *ResultCollectorSpec) {
	*out = *in
	if in.PolicyReports != nil {
		in, out := &in.PolicyReports, &out.PolicyReports
		*out = make([]PolicyReportRef, len(*in))
		copy(*out, *in)
	}
	if in.ClusterPolicyReports != nil {
		in, out := &in.ClusterPolicyReports, &out.ClusterPolicyReports
		*out = make([]PolicyReportRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultCollectorSpec.
func (in *ResultCollectorSpec) DeepCopy() *ResultCollectorSpec {
	if in == nil {
		return nil
	}
	out := new(ResultCollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultCollectorStatus) DeepCopyInto(out *ResultCollectorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultCollectorStatus.
func (in *ResultCollectorStatus) DeepCopy() *ResultCollectorStatus {
	if in == nil {
		return nil
	}
	out := new(ResultCollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Standard) DeepCopyInto(out *Standard) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]Category, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Standard.
func (in *Standard) DeepCopy() *Standard {
	if in == nil {
		return nil
	}
	out := new(Standard)
	in.DeepCopyInto(out)
	return out
}
