apiVersion: compliance-to-policy.io/v1alpha1
kind: ComplianceDeployment
metadata:
  labels:
    app.kubernetes.io/name: compliancedeployment
    app.kubernetes.io/instance: compliancedeployment-sample
    app.kubernetes.io/part-of: compliance-to-policy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: compliance-to-policy
  name: compliancedeployment-sample
spec:
  compliance:
    name: NIST_SP-800-53-HIGH # name of compliance
    catalog:
      url: https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json
    profile:
      url: https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_HIGH-baseline_profile.json
    componentDefinition:
      url: https://github.com/yana1205/policy-collection-resources/component-definitions/NIST_SP-800-53_rev5-baseline_component_definition.json
  policyResources: 
    url: https://github.com/yana1205/policy-collection-resources/resources
  clusterGroups:
    - name: cluster-nist-high # name of clusterGroup
      matchLabels:
        level: nist-high # label's key value pair of clusterlabel
  binding:
    compliance: NIST_SP-800-53-HIGH # compliance name
    clusterGroups:
    - cluster-nist-high # workspaceGroup name
  target:
    workspace: compliance-high # Edge-MC workspace to which C2P deploys generated resources
