## Append samples you want in your CSV to this file as resources ##
resources:
- compliance-to-policy_v1alpha1_compliancedeployment.yaml
- compliance-to-policy_v1alpha1_controlreference.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
