apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-collector
rules:
- apiGroups:
  - kyverno.io
  - wgpolicyk8s.io
  resources:
  - policies
  - clusterpolicies
  - policyreports
  - clusterpolicyreports
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyverno-collector
  namespace: c2p
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-collector
subjects:
- kind: ServiceAccount
  name: kyverno-collector
  namespace: c2p