# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/compliance-to-policy.io_compliancedeployments.yaml
- bases/compliance-to-policy.io_controlreferences.yaml
- bases/compliance-to-policy.io_controlreferencekcps.yaml
- bases/compliance-to-policy.io_resultcollectors.yaml
- bases/wgpolicyk8s.io_clusterpolicyreports.yaml
- bases/wgpolicyk8s.io_policyreports.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge: []
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_compliancedeployments.yaml
#- patches/webhook_in_controlreferences.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_compliancedeployments.yaml
#- patches/cainjection_in_controlreferences.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
