# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: validate

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - 'main'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with: 
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install for develompemnt
        run: |
          make install-dev
      - name: Unit Test
        run: |
          make test
      - name: Build
        run: |
          make build
      - name: Integration Test
        run: |
          pip install ./dist/*.tar.gz
          make it